
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 29 23:18:48 CST 2017
//----------------------------------------------------

package gui;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int tReserv = 23;
  public static final int tCadena = 18;
  public static final int tSimbolo = 3;
  public static final int tConj = 9;
  public static final int tTodo = 7;
  public static final int tCorcheteC = 25;
  public static final int tSep = 2;
  public static final int tError = 26;
  public static final int tCorcheteA = 24;
  public static final int tFlecha = 14;
  public static final int tRetorno = 15;
  public static final int tParentesisC = 17;
  public static final int tDoblePor = 8;
  public static final int tParentesisA = 16;
  public static final int tPuntoComa = 10;
  public static final int tExpConj = 13;
  public static final int tMas = 30;
  public static final int tDigito = 5;
  public static final int tAnd = 28;
  public static final int EOF = 0;
  public static final int tOr = 27;
  public static final int tCaracter = 6;
  public static final int error = 1;
  public static final int tYyCol = 22;
  public static final int tYyText = 20;
  public static final int tSignoI = 31;
  public static final int tYyRow = 21;
  public static final int tPor = 29;
  public static final int tId = 12;
  public static final int tEspecial = 4;
  public static final int tDosPuntos = 11;
  public static final int tComa = 19;
}

